[package]
name = "rust-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
hex = "0.4.3"
lazy_static = "1.5.0"
num-bigint = { version = "0.4.6", features = ["rand"] }
rand = "0.8.5"
ripemd = "0.1.3"
sha2 = "0.10.8"
